#objects = planet.o #solver.o 
#arma = -larmadillo -lblas -llapack

Project3.x: main.cpp planet.cpp solver.cpp
						g++ -o Program.x main.cpp planet.cpp solver.cpp
#planet.o: planet.cpp planet.h arma 
#					g++ -c planet.cpp

#EarthSun.x: EarthSun.cpp 
#						g++ -o EarthSun.x EarthSun.cpp  -larmadillo -lblas -llapack  



